
version: "3"

services:
  web:
    image: node:14
    command: node index.js
    working_dir: /home/app
    volumes:
      - ./guess-the-password-service/dist:/home/app
    environment:
      - LISTEN_PORT=3000
    ports:
      - "3000:3000"
  app:
    image: nginx:1.19.0
    entrypoint: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./guess-the-password-ui/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - web